### ISSUE TITLE
Prebellico 1.8.2 exception in thread UdpDiscoveryThread: TypeError: cannot use a string pattern on a bytes-like object

### ISSUE THREAD

**Issue by unixrox** [unixrox/prebellico#16]
Prebellico 1.8.2 throws an exception:

Exception in thread UdpDiscoveryThread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/prebellico/./prebellico.py", line 657, in udpDiscovery
    mailSlotString = re.findall("(?<=\n\x00)(?!\x03\x90\x00)[\w\-\!\@\$\%\^\&\(\)\+\=\[\]\{\}\'\;\~\`]{1,15}(?=\x00)|(?<=\x0f\x01U\xaa)(?!\x03\x90\x00)[\w\s\:\-\=\_\-\+\[\]\{\}\!\@\#\$\%\^\&\*\(\)\'\"\:\;\~\`]+(?=\x00)", ethernetPacket.child().child().child().get_buffer_as_string(), re.MULTILINE)
  File "/usr/lib/python3.10/re.py", line 240, in findall
    return _compile(pattern, flags).findall(string)
TypeError: cannot use a string pattern on a bytes-like object

**Comment by unixrox** [comment]
This is resolved in [1ebc9f2](https://github.com/unixrox/prebellico/commit/1ebc9f2343bedc37a517df397dd99e25bf2bd6e2). Thus, closing this issue.
